-- 013_spatial_ref_sys_revoke_write.sql
-- NON APPLIQUÉE — décision Soleil requise avant exécution en production
-- Préparée 2026-09-13, session Code (brief Soleil). Aucun REVOKE exécuté par cette session :
-- ce fichier est écrit, pas joué. Même régime que 012_contributions_native_capture.sql.
--
-- POURQUOI
-- Constat de l'audit Supabase du 2026-09-13 (`get_advisors`, sécurité) : `public.spatial_ref_sys`
-- (table système PostGIS, définitions de systèmes de référence de coordonnées SRID) a RLS
-- désactivée ET `anon`/`authenticated` y détiennent DELETE, INSERT, REFERENCES, SELECT, TRIGGER,
-- TRUNCATE, UPDATE (vérifié par `information_schema.role_table_grants`, pas supposé — même
-- classe de constat que INS-020/`CONTRIBUTIONS-GRANT-TABLE-REVOKE-COLONNE-INOPERANT-001` : droits
-- par défaut jamais révoqués, pas une régression d'une session). Les données elles-mêmes ne sont
-- pas sensibles (définitions de CRS, publiques par nature) — le risque est l'INTÉGRITÉ, pas la
-- confidentialité : n'importe quel visiteur muni de la seule clé anon publique peut aujourd'hui
-- TRUNCATE cette table, cassant toute opération PostGIS qui en dépendrait.
--
-- CE QUI RESTE : SELECT SEUL, ET POURQUOI
-- PostGIS lit `spatial_ref_sys` en interne (ST_Transform, ST_SetSRID et consorts) pour résoudre
-- les définitions proj4/WKT des SRID manipulés. Retirer SELECT casserait silencieusement toute
-- opération PostGIS qui aurait besoin d'y lire une définition — y compris via un chemin que cette
-- migration ne peut pas énumérer exhaustivement (fonction future, extension du schéma). SELECT
-- reste donc accordé à `anon`/`authenticated`, sans changement.
--
-- CONSTAT PRÉALABLE, DEMANDÉ AVANT D'ÉCRIRE CE FICHIER, PAS SUPPOSÉ :
-- aucune colonne de type `geometry`/`geography` n'existe dans le schéma `public`
-- (`information_schema.columns`, filtré sur `udt_name in ('geometry','geography')` → 0 ligne,
-- vérifié le 2026-09-13). Conséquence : aucune table applicative de ce projet ne stocke de type
-- spatial natif aujourd'hui — les colonnes de coordonnées sont des `double precision` lat/lon
-- ordinaires (`contributions`, `anfr_supports`, etc.), jamais un `geometry`. Ce que cette
-- migration protège n'est donc PAS un chemin de lecture spatiale déjà emprunté par l'application
-- en production aujourd'hui (aucun n'a été identifié) — c'est la CAPACITÉ PostGIS elle-même,
-- installée et disponible (fonctions ST_* exposées, cf. plus bas), pour un usage direct ou futur.
-- Ne pas confondre les deux dans la lecture de cette migration.
--
-- REFERENCES ET TRIGGER — TROUVÉS EN PLUS, INSTRUITS SÉPARÉMENT, PAS SUPPOSÉS ANODINS
-- `anon`/`authenticated` détiennent aussi REFERENCES (créer une contrainte de clé étrangère
-- pointant vers cette table) et TRIGGER (créer un déclencheur dessus) — deux privilèges de DDL,
-- pas de DML. Vérifié avant de trancher :
--   * PostgREST (la seule voie d'accès réelle pour `anon`/`authenticated` sur ce projet) ne
--     traduit AUCUN verbe HTTP vers `CREATE TABLE ... REFERENCES ...` ni `CREATE TRIGGER ...` —
--     ce sont des opérations de définition de schéma, hors du périmètre de l'API REST/RPC
--     qu'expose PostgREST (SELECT/INSERT/UPDATE/DELETE sur des lignes, exécution de fonctions
--     déjà définies). Aucun chemin HTTP normal ne peut donc les exercer aujourd'hui.
--   * CE N'EST PAS UNE RAISON DE LES GARDER. Le raisonnement retenu est le même que pour
--     INSERT/UPDATE/DELETE/TRUNCATE ci-dessus, pas un raisonnement différent : le privilège lui-
--     même est la frontière de sécurité réelle dans Postgres, pas la présence ou l'absence d'un
--     verbe HTTP qui l'exercerait aujourd'hui. S'appuyer sur « PostgREST ne l'expose pas » est un
--     argument propre à CETTE couche API, fragile si elle change ou si un autre chemin d'accès SQL
--     apparaît (injection dans une fonction, mauvaise configuration future, migration d'API) — pas
--     un argument structurel. `anon`/`authenticated` n'ont par ailleurs aucun besoin légitime de
--     créer une clé étrangère ou un déclencheur sur une table système PostGIS.
--   * DÉCISION : REFERENCES et TRIGGER partent avec les quatre autres. Même liste que le
--     brief l'a nommée (INSERT, UPDATE, DELETE, TRUNCATE) PLUS ces deux-là, pour la même raison
--     de fond — pas une extension non demandée : la question posée appelait une réponse motivée,
--     la voici.
--
-- EXPOSITION DE FONCTIONS POSTGIS À `anon` — CONSTAT ADJACENT, NON TRAITÉ ICI
-- La quasi-totalité des ~300 fonctions PostGIS installées (dont `find_srid`,
-- `postgis_transform_geometry`, `updategeometrysrid`, qui lisent `spatial_ref_sys`) apparaissent
-- exécutables par `anon` dans `information_schema.role_routine_grants` — cohérent avec le
-- comportement par défaut de PostgreSQL (EXECUTE accordé à PUBLIC à la création d'une fonction,
-- sauf REVOKE explicite), pas une configuration propre à ce projet. Ce constat est plus large que
-- le périmètre de cette migration (droits sur UNE table) et n'est pas instruit ici — signalé pour
-- ne pas être perdu, pas traité.

-- ═══════════════════════════════════════════════════════════════════════════════════════
-- CONSTAT DU 2026-09-13, APRÈS TENTATIVE D'APPLICATION — le REVOKE ci-dessous s'exécute SANS
-- ERREUR et SANS EFFET, pour une raison structurelle, pas la même que le REVOKE colonne de la
-- migration 012.
-- ═══════════════════════════════════════════════════════════════════════════════════════
-- `public.spatial_ref_sys` appartient à `supabase_admin` (`pg_tables.tableowner`), et chacun de
-- ses privilèges actuels vers `anon`/`authenticated` a été accordé PAR `supabase_admin`
-- (`information_schema.role_table_grants.grantor`). `supabase_admin` est un authentique
-- superutilisateur (`pg_roles.rolsuper = true`) — le rôle interne de la plateforme Supabase,
-- jamais exposé aux projets. Le rôle `postgres`, celui que ce fichier s'attend à voir exécuter
-- cette migration (MCP, SQL Editor, ou toute connexion `psql` standard fournie par Supabase),
-- **n'est PAS superutilisateur** (`rolsuper = false`) et **n'est membre d'aucun rôle nommé
-- `supabase_admin`** (`pg_auth_members`, vérifié). En PostgreSQL, seul le propriétaire d'un objet,
-- le rôle qui a effectué un GRANT (ou un rôle qui en hérite), ou un superutilisateur peut REVOKE
-- ce GRANT. `postgres` n'étant aucun des trois ici, PostgreSQL n'annule silencieusement RIEN — pas
-- d'erreur, pas d'avertissement remonté par l'outil d'application, juste un REVOKE qui ne retranche
-- rien à personne.
--
-- VÉRIFIÉ PAR LE CHEMIN CLIENT RÉEL, PAS SEULEMENT DÉDUIT DE LA TABLE DES PRIVILÈGES : après
-- application de ce fichier, `POST /rest/v1/spatial_ref_sys` avec la seule clé anon publique a
-- répondu `201 Created` — un visiteur anonyme peut toujours écrire dans cette table. Ligne de test
-- supprimée immédiatement par connexion privilégiée (`anon` n'a pas de policy RLS DELETE ici non
-- plus ; RLS reste désactivée sur cette table, cf. fichier ci-dessus — seul le GRANT était visé).
--
-- CONSÉQUENCE — CE QUE CE FICHIER NE PEUT PAS FAIRE, PAR AUCUNE VOIE STANDARD : ni cette session,
-- ni Soleil depuis le SQL Editor du tableau de bord Supabase (qui se connecte sous le même rôle
-- `postgres`) ne peuvent exécuter ce REVOKE avec effet, en l'état. Ce n'est pas une question
-- d'outil ou de méthode d'exécution — c'est une frontière de propriété PostgreSQL que le rôle
-- `postgres` ne franchit pas sur ce projet. Toute remédiation réelle demande soit une intervention
-- côté support Supabase (seul `supabase_admin` peut REVOKE ce qu'il a accordé), soit une autre
-- voie non instruite ici (ex. `ALTER TABLE ... OWNER TO postgres` — qui échouerait pour la MÊME
-- raison : cette commande exige aussi d'être propriétaire ou superutilisateur). Aucune des deux
-- n'est tentée par ce fichier.
--
-- Ligne conservée ci-dessous, commentée et non supprimée, plutôt que le fichier n'affirme un
-- retrait qui n'a pas eu lieu — même règle que la ligne REVOKE de la migration 012.
--
-- revoke insert, update, delete, truncate, references, trigger
--   on public.spatial_ref_sys
--   from anon, authenticated;

-- ROLLBACK — non exécuté, écrit avec la migration comme demandé.
-- Chaque privilège listé explicitement, dans le même ordre : un ROLLBACK qui dirait juste
-- « regrant tout » masquerait lequel a été retiré si cette ligne est relue plus tard sans le
-- REVOKE sous les yeux.
--
-- grant insert, update, delete, truncate, references, trigger
--   on public.spatial_ref_sys
--   to anon, authenticated;
--
-- ═══════════════════════════════════════════════════════════════════════════════════════
-- VÉRIFICATION APRÈS APPLICATION — écrite pour être lancée une fois la migration jouée.
-- Points 1 et 5 : DÉJÀ JOUÉS, le 2026-09-13, contre l'échec d'application ci-dessus documenté —
-- résultat rapporté dans chaque point, pas une attente. Points 2/3/4 : non rejoués (SELECT n'a
-- jamais été touché, rien ne les distingue d'avant la tentative) — laissés tels quels, prêts si
-- une application réelle finit par avoir lieu.
-- ═══════════════════════════════════════════════════════════════════════════════════════
--
-- 1) Droits : `select grantee, privilege_type from information_schema.role_table_grants
--    where table_schema='public' and table_name='spatial_ref_sys' and grantee in
--    ('anon','authenticated');`
--    ATTENDU : seul SELECT reste listé pour les deux rôles.
--    OBTENU LE 2026-09-13 : les 7 privilèges d'origine, identiques, pour les deux rôles — le
--    REVOKE n'a rien retranché (cf. constat d'échec d'application ci-dessus).
--
-- 2) Lecture spatiale directe, chemin privilégié (prouve que SELECT + les données restent
--    intactes, ne prouve PAS le chemin client) :
--      select srtext from public.spatial_ref_sys where srid = 4326;
--    ATTENDU : une ligne retournée (WGS 84), inchangée par rapport à avant la migration.
--
-- 3) Opération PostGIS bout en bout qui CONSULTE spatial_ref_sys en interne (transformation
--    d'un point WGS84 vers Web Mercator — 4326 → 3857, deux SRID distincts, donc une vraie
--    résolution de définition, pas un no-op) :
--      select ST_AsText(ST_Transform(ST_SetSRID(ST_MakePoint(9.1, 42.1), 4326), 3857));
--    ATTENDU SI ÇA MARCHE : une géométrie POINT en coordonnées Web Mercator, ex.
--    `POINT(1013071... 5169499...)` — confirme que la lecture SELECT restante suffit à PostGIS.
--    ATTENDU SI ÇA RATE : une erreur `could not find corresponding SRID` ou équivalent —
--    signerait un SELECT cassé par erreur, à corriger avant toute chose.
--
-- 4) Chemin client réel, si un jour une fonction l'expose : `POST /rest/v1/rpc/<fonction>`
--    avec la clé anon publique, sur une fonction appelant ST_Transform/find_srid. Aucune fonction
--    de ce type n'est identifiée comme réellement appelée par l'application aujourd'hui (aucune
--    colonne geometry/geography en base, cf. plus haut) — ce volet reste donc une procédure prête
--    à jouer si un tel usage apparaît, pas un test qui a un objet concret à la date de cette
--    migration. Ne pas le sauter pour autant s'il devient pertinent : c'est le seul des quatre
--    volets qui teste le chemin PostgREST réel plutôt qu'une connexion privilégiée.
--
-- 5) Contrôle négatif, confirme que le retrait a un effet réel (pas un no-op comme le REVOKE
--    colonne de la migration 012) : depuis une connexion authentifiée en `anon` (pas privilégiée),
--    `INSERT INTO public.spatial_ref_sys (srid, auth_name, auth_srid) VALUES (900001, 'test',
--    900001);` — ATTENDU : rejet `permission denied for table spatial_ref_sys` (42501).
--    OBTENU LE 2026-09-13, chemin client réel (`POST /rest/v1/spatial_ref_sys`, clé anon
--    publique) : `201 Created`. L'INSERT a réussi — la migration n'a pas eu l'effet voulu, cf.
--    constat d'échec d'application ci-dessus (barrière de propriété `supabase_admin`/`postgres`,
--    pas une répétition du défaut de la 012). Ligne de test nettoyée par connexion privilégiée
--    immédiatement après ce constat, comme prescrit ici.
